"""
backend/data/archive_store.py

PURPOSE:
  The satellite image archive — a collection of 100 reference scenes
  with pre-computed feature vectors and embeddings.

  When a user uploads an image, we compare its embedding against all
  archive embeddings using cosine similarity to find the most similar
  historical scenes.

WHY THIS DESIGN:
  In production (ISRO Bhuvan scale), the archive would be:
    - 2.48 million satellite scenes
    - Stored in a FAISS GPU index
    - Embeddings generated by a fine-tuned ResNet/ViT model
    - Queried with Approximate Nearest Neighbor (ANN) search

  For this system, we have 100 scenes with:
    - Hand-crafted feature profiles based on domain knowledge
    - Deterministic embeddings computed from these profiles
    - Realistic Indian coordinates and satellite metadata
    - Diverse scene types (flood, vegetation, urban, agriculture, coastal)

DETERMINISM GUARANTEE:
  Archive embeddings are computed from feature profiles, not random vectors.
  The SAME feature profile ALWAYS produces the SAME embedding.
  This means:
    1. Archive is reproducible (no seed needed)
    2. A flood image → high water_index → high cosine sim with flood archive entries
    3. Results make physical sense (not randomly similar)

  PROOF:
    Archive flood entry: water_index ≈ 0.78
    Uploaded flood image: water_index ≈ 0.74 (from feature extraction)
    Both embeddings point "toward" the water_index dimension
    Dot product is high → high cosine similarity ✓

THUMBNAIL URLS:
  Archive entries use curated Unsplash photo IDs that visually match the scene type.
  These are static display thumbnails — not actual satellite imagery.
  Production would serve real 512×512 scene crops from Bhuvan storage.

INPUT:  None (called at server startup)
OUTPUT: Initialized archive with 100 entries + pre-computed embedding matrix

COMPLEXITY: O(100 × 32) for embedding computation = trivial
"""

from __future__ import annotations

from typing import Any

import numpy as np

from ai.embeddings.embedding_generator import EmbeddingGenerator, FEATURE_WEIGHTS
from ai.image_processing.feature_extractor import FEATURE_NAMES

# ── Scene category feature profiles ──────────────────────────────────────────
# Each profile is a 32-dimensional numpy array matching FEATURE_NAMES ordering.
# Values are in [0, 1] and represent the "ideal" characteristics of that scene type.
#
# HOW THESE VALUES WERE CHOSEN:
#   Remote sensing textbooks + ISRO operational guidelines define what each
#   scene type "looks like" in terms of spectral indices and texture.
#   These are not arbitrary — they encode real physical domain knowledge.
#
# REMINDER: FEATURE_NAMES order:
#  [0]contrast, [1]entropy, [2]homogeneity, [3]energy, [4]correlation,
#  [5]edge_density, [6]mean_gradient, [7]coarseness, [8]directionality,
#  [9]local_std, [10]h_gradient, [11]v_gradient,
#  [12]mean_r, [13]mean_g, [14]mean_b, [15]std_r, [16]std_g, [17]std_b,
#  [18]entropy_r, [19]entropy_g,
#  [20]vegetation_index, [21]water_index, [22]brightness, [23]saturation,
#  [24]warm_ratio, [25]cool_ratio,
#  [26]quad_tl, [27]quad_tr, [28]quad_bl, [29]quad_br, [30]spatial_var,
#  [31]complexity

SCENE_PROFILES: dict[str, np.ndarray] = {

    # ── FLOOD / INUNDATION ─────────────────────────────────────────────────
    # Water is spectrally "cold" (high blue, low red reflectance)
    # Flooded areas are smooth (low texture contrast)
    # Very few edges (water surface has no structure)
    "flood": np.array([
        0.10,  # contrast: very low (smooth water surface)
        0.55,  # entropy: medium-low (some surface variation from waves)
        0.85,  # homogeneity: very high (water pixels are very uniform)
        0.40,  # energy: medium (moderate histogram concentration)
        0.82,  # correlation: high (adjacent water pixels very similar)
        0.07,  # edge_density: very low (almost no edges in open water)
        0.06,  # mean_gradient: very low
        0.88,  # coarseness: very high (large uniform water regions)
        0.50,  # directionality: neutral
        0.03,  # local_std: very low (uniform texture)
        0.05,  # h_gradient: low
        0.05,  # v_gradient: low
        0.35,  # mean_r: low (water absorbs red light)
        0.42,  # mean_g: medium-low
        0.62,  # mean_b: HIGH (water scatters blue light most)
        0.07,  # std_r: very low (uniform channel)
        0.08,  # std_g: low
        0.10,  # std_b: low
        0.42,  # entropy_r: low
        0.45,  # entropy_g: low
        0.18,  # vegetation_index: VERY LOW (water suppresses NDVI)
        0.78,  # water_index: VERY HIGH ← critical flood discriminator
        0.46,  # brightness: medium-low
        0.16,  # saturation: low (water is blueish-gray, not colorful)
        0.30,  # warm_ratio: low (not warm/red-dominated)
        0.68,  # cool_ratio: HIGH (blue-dominated → high cool ratio)
        0.44,  # quad_tl
        0.46,  # quad_tr
        0.45,  # quad_bl
        0.46,  # quad_br
        0.02,  # spatial_var: very low (uniform flood extent)
        0.31,  # complexity: low
    ]),

    # ── VEGETATION / FOREST ────────────────────────────────────────────────
    # Dense forest reflects strongly in green (chlorophyll absorption red, reflects NIR)
    # High vegetation_index is the strongest signal
    # Medium texture from forest canopy structure
    "vegetation": np.array([
        0.28,  # contrast: medium (canopy variation)
        0.72,  # entropy: high (complex forest structure)
        0.52,  # homogeneity: medium (canopy gaps create variation)
        0.18,  # energy: low (many different intensity levels)
        0.55,  # correlation: medium
        0.28,  # edge_density: medium-low (forest edges between trees)
        0.22,  # mean_gradient: medium-low
        0.45,  # coarseness: medium (intermediate texture scale)
        0.48,  # directionality: near-neutral (random canopy orientation)
        0.18,  # local_std: medium
        0.20,  # h_gradient: medium
        0.21,  # v_gradient: medium
        0.22,  # mean_r: low (vegetation absorbs red for photosynthesis)
        0.52,  # mean_g: HIGH (vegetation strongly reflects green)
        0.28,  # mean_b: low-medium
        0.08,  # std_r: low
        0.10,  # std_g: low-medium
        0.08,  # std_b: low
        0.48,  # entropy_r: medium
        0.58,  # entropy_g: medium-high
        0.85,  # vegetation_index: VERY HIGH ← critical vegetation discriminator
        0.22,  # water_index: low (vegetation has low water spectral response)
        0.34,  # brightness: medium-low (dark forest absorbs light)
        0.32,  # saturation: medium (green-dominant color)
        0.27,  # warm_ratio: low (not red/warm)
        0.55,  # cool_ratio: medium-high (green + blue dominate)
        0.33,  # quad_tl
        0.35,  # quad_tr
        0.34,  # quad_bl
        0.33,  # quad_br
        0.02,  # spatial_var: low (uniform canopy)
        0.50,  # complexity: medium
    ]),

    # ── URBAN / BUILT-UP ──────────────────────────────────────────────────
    # Cities have regular geometric patterns → high edge density
    # Mixed surfaces → moderate vegetation, low water
    # Buildings reflect broadly across spectrum → moderate brightness
    "urban": np.array([
        0.52,  # contrast: high (building shadows, rooftop variation)
        0.78,  # entropy: high (complex city structure)
        0.38,  # homogeneity: medium-low (lots of variation)
        0.12,  # energy: low (many different intensity levels)
        0.38,  # correlation: medium-low (irregular patterns)
        0.68,  # edge_density: VERY HIGH ← critical urban discriminator
        0.52,  # mean_gradient: high
        0.28,  # coarseness: low-medium (fine-grained texture of buildings)
        0.55,  # directionality: slightly horizontal (street grid)
        0.35,  # local_std: medium-high
        0.48,  # h_gradient: high
        0.42,  # v_gradient: high
        0.48,  # mean_r: medium (mixed surfaces)
        0.46,  # mean_g: medium
        0.44,  # mean_b: medium-low
        0.18,  # std_r: medium
        0.17,  # std_g: medium
        0.16,  # std_b: medium
        0.65,  # entropy_r: high (complex city)
        0.64,  # entropy_g: high
        0.25,  # vegetation_index: low-medium (some parks, trees)
        0.28,  # water_index: low (minimal water unless rivers present)
        0.46,  # brightness: medium
        0.05,  # saturation: very low (urban is grayish from concrete)
        0.36,  # warm_ratio: slightly warm (concrete, brick, roads)
        0.46,  # cool_ratio: medium
        0.46,  # quad_tl
        0.45,  # quad_tr
        0.47,  # quad_bl
        0.46,  # quad_br
        0.02,  # spatial_var: low (buildings distributed uniformly)
        0.73,  # complexity: HIGH (urban = complex)
    ]),

    # ── AGRICULTURE / FARMLAND ────────────────────────────────────────────
    # Irrigated fields have moderate vegetation_index
    # Regular field patterns → moderate directionality
    # Warm-toned soil between crops → warm_ratio elevated
    "agriculture": np.array([
        0.22,  # contrast: low-medium (crop rows create some gradient)
        0.60,  # entropy: medium-high (multiple crop types)
        0.62,  # homogeneity: medium-high (fields are relatively uniform)
        0.25,  # energy: low-medium
        0.68,  # correlation: high (crops have regular patterns)
        0.22,  # edge_density: low-medium (field boundaries create lines)
        0.18,  # mean_gradient: low
        0.58,  # coarseness: medium-high (large uniform fields)
        0.62,  # directionality: slightly directional (plowing patterns)
        0.12,  # local_std: low (uniform within fields)
        0.17,  # h_gradient: low-medium
        0.14,  # v_gradient: low
        0.38,  # mean_r: medium-low
        0.48,  # mean_g: medium-high (crop green)
        0.30,  # mean_b: medium-low
        0.12,  # std_r
        0.12,  # std_g
        0.09,  # std_b
        0.52,  # entropy_r: medium
        0.55,  # entropy_g: medium
        0.68,  # vegetation_index: HIGH but lower than forest (crops, not dense forest)
        0.30,  # water_index: low-medium (irrigated but not flooded)
        0.38,  # brightness: medium-low
        0.28,  # saturation: medium (green + warm soil mix)
        0.40,  # warm_ratio: slightly warm (soil between crops)
        0.50,  # cool_ratio: medium
        0.37,  # quad_tl
        0.40,  # quad_tr
        0.38,  # quad_bl
        0.41,  # quad_br
        0.03,  # spatial_var: low (fields are patchwork but at large scale)
        0.41,  # complexity: medium
    ]),

    # ── COASTAL / WATER BODY ──────────────────────────────────────────────
    # Mixed water + land → intermediate water_index
    # Coastal edges → some edge density from land-water boundary
    # Higher spatial variance than open water
    "coastal": np.array([
        0.25,  # contrast: medium-low
        0.62,  # entropy: medium-high (mixed scene)
        0.62,  # homogeneity: medium-high
        0.28,  # energy: low-medium
        0.65,  # correlation: medium-high
        0.25,  # edge_density: medium-low (coastline edge)
        0.18,  # mean_gradient: low-medium
        0.65,  # coarseness: medium-high
        0.45,  # directionality: neutral
        0.12,  # local_std: low
        0.16,  # h_gradient
        0.16,  # v_gradient
        0.38,  # mean_r
        0.44,  # mean_g
        0.52,  # mean_b: elevated (ocean/water component)
        0.12,  # std_r
        0.12,  # std_g
        0.13,  # std_b
        0.50,  # entropy_r
        0.52,  # entropy_g
        0.38,  # vegetation_index: medium-low (some coastal vegetation)
        0.58,  # water_index: HIGH (ocean + estuaries)
        0.44,  # brightness
        0.20,  # saturation: low-medium
        0.32,  # warm_ratio: low (water-dominated)
        0.60,  # cool_ratio: high (ocean blue)
        0.40,  # quad_tl (land)
        0.44,  # quad_tr (water)
        0.42,  # quad_bl (land)
        0.48,  # quad_br (water)
        0.08,  # spatial_var: elevated (land-water boundary creates variation)
        0.43,  # complexity: medium
    ]),
}


# ── Archive scene catalog ─────────────────────────────────────────────────────
# 100 scenes: 20 per category × 5 categories
# Each entry: id, satellite, sensor_type, location, timestamp, event_type, thumbnail

# Curated Unsplash photo IDs by category (visually representative)
_THUMBS = {
    "flood":       [
        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&q=80",
        "https://images.unsplash.com/photo-1504370805625-d32c54b16100?w=300&q=80",
        "https://images.unsplash.com/photo-1547683905-f686c993aae5?w=300&q=80",
        "https://images.unsplash.com/photo-1591824438708-ce405f36ba3d?w=300&q=80",
    ],
    "vegetation":  [
        "https://images.unsplash.com/photo-1448375240586-882707db888b?w=300&q=80",
        "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=300&q=80",
        "https://images.unsplash.com/photo-1573408301185-9519f94804b4?w=300&q=80",
        "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=300&q=80",
    ],
    "urban":       [
        "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=300&q=80",
        "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=300&q=80",
        "https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=300&q=80",
        "https://images.unsplash.com/photo-1460472178825-e5240623afd5?w=300&q=80",
    ],
    "agriculture": [
        "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=300&q=80",
        "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=300&q=80",
        "https://images.unsplash.com/photo-1523741543316-beb7fc7023d8?w=300&q=80",
        "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=300&q=80",
    ],
    "coastal":     [
        "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=300&q=80",
        "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=300&q=80",
        "https://images.unsplash.com/photo-1471922694854-ff1b63b20054?w=300&q=80",
        "https://images.unsplash.com/photo-1455577380025-4321f1e1dca7?w=300&q=80",
    ],
}

_SCENE_CATALOG: list[dict[str, Any]] = [
    # ── FLOOD scenes (India: river systems, monsoon flooding) ───────────────
    {"id": "F001", "satellite": "RISAT-2B",     "sensor_type": "SAR",          "location": "Brahmaputra Basin, Assam",    "lat": 26.14, "lng": 91.73, "date": "2024-07-15", "event_type": "flood",  "category": "flood",       "resolution_m": 1},
    {"id": "F002", "satellite": "Sentinel-1A",  "sensor_type": "SAR",          "location": "Assam Floodplain",            "lat": 26.50, "lng": 92.10, "date": "2024-07-12", "event_type": "flood",  "category": "flood",       "resolution_m": 5},
    {"id": "F003", "satellite": "RISAT-2B",     "sensor_type": "SAR",          "location": "Brahmaputra Basin",           "lat": 25.90, "lng": 89.82, "date": "2022-08-14", "event_type": "flood",  "category": "flood",       "resolution_m": 1},
    {"id": "F004", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Majuli Island, Assam",        "lat": 27.01, "lng": 94.22, "date": "2023-06-22", "event_type": "flood",  "category": "flood",       "resolution_m": 10},
    {"id": "F005", "satellite": "RISAT-2B",     "sensor_type": "SAR",          "location": "Ganga Floodplain, Bihar",     "lat": 25.38, "lng": 85.54, "date": "2023-08-08", "event_type": "flood",  "category": "flood",       "resolution_m": 1},
    {"id": "F006", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Bihar Floods",                "lat": 26.12, "lng": 86.91, "date": "2022-08-01", "event_type": "flood",  "category": "flood",       "resolution_m": 30},
    {"id": "F007", "satellite": "Sentinel-1B",  "sensor_type": "SAR",          "location": "Kerala Backwaters Flood",     "lat": 9.55,  "lng": 76.52, "date": "2023-07-30", "event_type": "flood",  "category": "flood",       "resolution_m": 5},
    {"id": "F008", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Chalakudy River, Kerala",     "lat": 10.32, "lng": 76.42, "date": "2024-06-18", "event_type": "flood",  "category": "flood",       "resolution_m": 10},
    {"id": "F009", "satellite": "RISAT-2B",     "sensor_type": "SAR",          "location": "Mahanadi Delta, Odisha",      "lat": 20.28, "lng": 86.51, "date": "2023-09-14", "event_type": "flood",  "category": "flood",       "resolution_m": 1},
    {"id": "F010", "satellite": "Sentinel-1A",  "sensor_type": "SAR",          "location": "Baitarani River, Odisha",     "lat": 21.53, "lng": 86.28, "date": "2022-09-21", "event_type": "flood",  "category": "flood",       "resolution_m": 5},
    {"id": "F011", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Damodar Valley, Bengal",      "lat": 23.12, "lng": 87.08, "date": "2024-08-04", "event_type": "flood",  "category": "flood",       "resolution_m": 24},
    {"id": "F012", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Teesta River, Bengal",        "lat": 26.45, "lng": 88.71, "date": "2023-10-03", "event_type": "flood",  "category": "flood",       "resolution_m": 10},
    {"id": "F013", "satellite": "ALOS-2",       "sensor_type": "SAR",          "location": "Godavari Delta, Andhra",      "lat": 16.92, "lng": 81.72, "date": "2022-07-22", "event_type": "flood",  "category": "flood",       "resolution_m": 3},
    {"id": "F014", "satellite": "Sentinel-1B",  "sensor_type": "SAR",          "location": "Krishna River Basin",         "lat": 16.50, "lng": 80.60, "date": "2024-09-02", "event_type": "flood",  "category": "flood",       "resolution_m": 5},
    {"id": "F015", "satellite": "RISAT-2B",     "sensor_type": "SAR",          "location": "Ravi River, Punjab",          "lat": 32.22, "lng": 75.12, "date": "2023-08-19", "event_type": "flood",  "category": "flood",       "resolution_m": 1},
    {"id": "F016", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Chenab River Flood, Punjab",  "lat": 31.98, "lng": 74.85, "date": "2022-08-30", "event_type": "flood",  "category": "flood",       "resolution_m": 30},
    {"id": "F017", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Yamuna Floodplain, Delhi",    "lat": 28.72, "lng": 77.22, "date": "2023-07-12", "event_type": "flood",  "category": "flood",       "resolution_m": 10},
    {"id": "F018", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Gandak River, Bihar",         "lat": 26.60, "lng": 84.48, "date": "2024-07-28", "event_type": "flood",  "category": "flood",       "resolution_m": 24},
    {"id": "F019", "satellite": "Sentinel-1A",  "sensor_type": "SAR",          "location": "Mahi River, Gujarat",         "lat": 22.38, "lng": 73.28, "date": "2023-08-27", "event_type": "flood",  "category": "flood",       "resolution_m": 5},
    {"id": "F020", "satellite": "RISAT-2B",     "sensor_type": "SAR",          "location": "Banas River, Rajasthan",      "lat": 25.15, "lng": 75.48, "date": "2022-09-05", "event_type": "flood",  "category": "flood",       "resolution_m": 1},

    # ── VEGETATION / FOREST scenes ────────────────────────────────────────
    {"id": "V001", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Silent Valley, Kerala",       "lat": 11.08, "lng": 76.47, "date": "2024-02-14", "event_type": "none",   "category": "vegetation",  "resolution_m": 10},
    {"id": "V002", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Kaziranga National Park",     "lat": 26.58, "lng": 93.18, "date": "2024-01-22", "event_type": "none",   "category": "vegetation",  "resolution_m": 24},
    {"id": "V003", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Jim Corbett NP, Uttarakhand", "lat": 29.53, "lng": 78.78, "date": "2023-11-08", "event_type": "none",   "category": "vegetation",  "resolution_m": 10},
    {"id": "V004", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Sundarbans Mangroves, Bengal","lat": 21.94, "lng": 88.88, "date": "2023-12-15", "event_type": "none",   "category": "vegetation",  "resolution_m": 30},
    {"id": "V005", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Western Ghats, Karnataka",    "lat": 14.02, "lng": 75.22, "date": "2024-03-10", "event_type": "none",   "category": "vegetation",  "resolution_m": 10},
    {"id": "V006", "satellite": "ALOS-2",       "sensor_type": "SAR",          "location": "Shola Forest, Nilgiris",      "lat": 11.42, "lng": 76.68, "date": "2023-09-28", "event_type": "none",   "category": "vegetation",  "resolution_m": 3},
    {"id": "V007", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Namdapha NP, Arunachal",      "lat": 27.52, "lng": 97.02, "date": "2024-04-05", "event_type": "none",   "category": "vegetation",  "resolution_m": 10},
    {"id": "V008", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Periyar Tiger Reserve",       "lat": 9.47,  "lng": 77.13, "date": "2023-10-18", "event_type": "none",   "category": "vegetation",  "resolution_m": 24},
    {"id": "V009", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Gir Forest, Gujarat",         "lat": 21.12, "lng": 70.82, "date": "2024-01-30", "event_type": "none",   "category": "vegetation",  "resolution_m": 30},
    {"id": "V010", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Pench NP, Madhya Pradesh",    "lat": 21.98, "lng": 79.30, "date": "2023-11-25", "event_type": "none",   "category": "vegetation",  "resolution_m": 10},
    {"id": "V011", "satellite": "Sentinel-1A",  "sensor_type": "SAR",          "location": "Aravalli Forest, Rajasthan",  "lat": 26.88, "lng": 73.18, "date": "2024-02-28", "event_type": "none",   "category": "vegetation",  "resolution_m": 5},
    {"id": "V012", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Parambikulam Reserve, Kerala","lat": 10.35, "lng": 76.72, "date": "2023-12-02", "event_type": "none",   "category": "vegetation",  "resolution_m": 10},
    {"id": "V013", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Deccan Forest, Karnataka",    "lat": 13.28, "lng": 77.08, "date": "2024-03-22", "event_type": "none",   "category": "vegetation",  "resolution_m": 24},
    {"id": "V014", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Terai Arc, Uttarakhand",      "lat": 28.92, "lng": 79.22, "date": "2023-10-12", "event_type": "deforestation", "category": "vegetation", "resolution_m": 30},
    {"id": "V015", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Andaman Dense Forest",        "lat": 12.28, "lng": 92.82, "date": "2024-01-08", "event_type": "none",   "category": "vegetation",  "resolution_m": 10},
    {"id": "V016", "satellite": "ALOS-2",       "sensor_type": "SAR",          "location": "Northeast India Bamboo Forest","lat": 25.58, "lng": 94.22, "date": "2023-09-15", "event_type": "none",   "category": "vegetation",  "resolution_m": 3},
    {"id": "V017", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Dibru-Saikhowa NP, Assam",    "lat": 27.38, "lng": 95.28, "date": "2024-04-18", "event_type": "none",   "category": "vegetation",  "resolution_m": 10},
    {"id": "V018", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Satpura Range, MP",           "lat": 22.85, "lng": 77.52, "date": "2023-11-05", "event_type": "none",   "category": "vegetation",  "resolution_m": 24},
    {"id": "V019", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Simlipal NP, Odisha",         "lat": 21.62, "lng": 86.48, "date": "2024-02-05", "event_type": "none",   "category": "vegetation",  "resolution_m": 30},
    {"id": "V020", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Nagarhole NP, Karnataka",     "lat": 11.98, "lng": 76.12, "date": "2023-12-28", "event_type": "none",   "category": "vegetation",  "resolution_m": 10},

    # ── URBAN / BUILT-UP scenes ───────────────────────────────────────────
    {"id": "U001", "satellite": "Cartosat-3",   "sensor_type": "Optical",      "location": "Central Delhi",               "lat": 28.61, "lng": 77.22, "date": "2024-05-12", "event_type": "none",   "category": "urban",       "resolution_m": 0},
    {"id": "U002", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Mumbai Urban Core",           "lat": 19.07, "lng": 72.88, "date": "2024-04-08", "event_type": "none",   "category": "urban",       "resolution_m": 10},
    {"id": "U003", "satellite": "Cartosat-3",   "sensor_type": "Optical",      "location": "Bangalore IT Hub",            "lat": 12.97, "lng": 77.59, "date": "2024-03-18", "event_type": "none",   "category": "urban",       "resolution_m": 0},
    {"id": "U004", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Hyderabad HITEC City",        "lat": 17.44, "lng": 78.38, "date": "2024-02-22", "event_type": "none",   "category": "urban",       "resolution_m": 24},
    {"id": "U005", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Chennai Suburbs",             "lat": 13.09, "lng": 80.27, "date": "2024-01-15", "event_type": "none",   "category": "urban",       "resolution_m": 10},
    {"id": "U006", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Kolkata Metropolitan Area",   "lat": 22.57, "lng": 88.36, "date": "2023-12-10", "event_type": "none",   "category": "urban",       "resolution_m": 30},
    {"id": "U007", "satellite": "Cartosat-3",   "sensor_type": "Optical",      "location": "Pune Urban Expansion",        "lat": 18.52, "lng": 73.88, "date": "2024-05-28", "event_type": "urban_expansion", "category": "urban", "resolution_m": 0},
    {"id": "U008", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Ahmedabad Smart City",        "lat": 23.02, "lng": 72.57, "date": "2024-04-22", "event_type": "none",   "category": "urban",       "resolution_m": 10},
    {"id": "U009", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Surat Industrial Zone",       "lat": 21.17, "lng": 72.83, "date": "2023-11-18", "event_type": "none",   "category": "urban",       "resolution_m": 24},
    {"id": "U010", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Jaipur Heritage Area",        "lat": 26.92, "lng": 75.82, "date": "2024-03-05", "event_type": "none",   "category": "urban",       "resolution_m": 10},
    {"id": "U011", "satellite": "Cartosat-3",   "sensor_type": "Optical",      "location": "Lucknow Urban Growth",        "lat": 26.85, "lng": 80.95, "date": "2024-02-12", "event_type": "urban_expansion", "category": "urban", "resolution_m": 0},
    {"id": "U012", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Indore Industrial",           "lat": 22.72, "lng": 75.86, "date": "2023-10-28", "event_type": "none",   "category": "urban",       "resolution_m": 30},
    {"id": "U013", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Kochi Urban Core",            "lat": 9.93,  "lng": 76.27, "date": "2024-04-15", "event_type": "none",   "category": "urban",       "resolution_m": 10},
    {"id": "U014", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Nagpur City",                 "lat": 21.15, "lng": 79.08, "date": "2023-12-22", "event_type": "none",   "category": "urban",       "resolution_m": 24},
    {"id": "U015", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Vizag Steel City",            "lat": 17.69, "lng": 83.22, "date": "2024-01-28", "event_type": "none",   "category": "urban",       "resolution_m": 10},
    {"id": "U016", "satellite": "Cartosat-3",   "sensor_type": "Optical",      "location": "Chandigarh Planned City",     "lat": 30.73, "lng": 76.78, "date": "2024-03-28", "event_type": "none",   "category": "urban",       "resolution_m": 0},
    {"id": "U017", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Bhopal Urban Lakes",          "lat": 23.27, "lng": 77.42, "date": "2023-11-14", "event_type": "none",   "category": "urban",       "resolution_m": 30},
    {"id": "U018", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Gurgaon Millennium City",     "lat": 28.47, "lng": 77.03, "date": "2024-05-05", "event_type": "none",   "category": "urban",       "resolution_m": 10},
    {"id": "U019", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Coimbatore Industrial",       "lat": 11.01, "lng": 76.96, "date": "2023-12-08", "event_type": "none",   "category": "urban",       "resolution_m": 24},
    {"id": "U020", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Thane Urban Sprawl",          "lat": 19.21, "lng": 72.98, "date": "2024-02-18", "event_type": "urban_expansion", "category": "urban", "resolution_m": 10},

    # ── AGRICULTURE / FARMLAND scenes ─────────────────────────────────────
    {"id": "A001", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Punjab Wheat Fields",         "lat": 30.92, "lng": 75.85, "date": "2024-04-02", "event_type": "none",   "category": "agriculture", "resolution_m": 10},
    {"id": "A002", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Haryana Crop Monitoring",     "lat": 29.95, "lng": 76.82, "date": "2024-03-18", "event_type": "none",   "category": "agriculture", "resolution_m": 24},
    {"id": "A003", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "UP Gangetic Plains, Crops",   "lat": 27.12, "lng": 80.52, "date": "2024-01-28", "event_type": "none",   "category": "agriculture", "resolution_m": 30},
    {"id": "A004", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Madhya Pradesh Soy Fields",   "lat": 23.52, "lng": 77.88, "date": "2023-10-05", "event_type": "none",   "category": "agriculture", "resolution_m": 10},
    {"id": "A005", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Maharashtra Sugarcane",       "lat": 17.68, "lng": 74.22, "date": "2023-11-28", "event_type": "none",   "category": "agriculture", "resolution_m": 24},
    {"id": "A006", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Karnataka Paddy Fields",      "lat": 14.68, "lng": 76.08, "date": "2024-02-08", "event_type": "none",   "category": "agriculture", "resolution_m": 10},
    {"id": "A007", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Andhra Pradesh Cotton",       "lat": 16.52, "lng": 79.88, "date": "2023-12-18", "event_type": "none",   "category": "agriculture", "resolution_m": 30},
    {"id": "A008", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "West Bengal Rice Fields",     "lat": 23.28, "lng": 88.12, "date": "2023-09-22", "event_type": "none",   "category": "agriculture", "resolution_m": 10},
    {"id": "A009", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Gujarat Groundnut Farms",     "lat": 21.88, "lng": 70.58, "date": "2024-03-05", "event_type": "none",   "category": "agriculture", "resolution_m": 24},
    {"id": "A010", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Rajasthan Canal Irrigation",  "lat": 29.02, "lng": 72.48, "date": "2024-02-22", "event_type": "none",   "category": "agriculture", "resolution_m": 10},
    {"id": "A011", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Tamil Nadu Paddy Delta",      "lat": 10.82, "lng": 79.68, "date": "2023-10-28", "event_type": "none",   "category": "agriculture", "resolution_m": 30},
    {"id": "A012", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Assam Tea Gardens",           "lat": 27.08, "lng": 93.48, "date": "2024-04-12", "event_type": "none",   "category": "agriculture", "resolution_m": 10},
    {"id": "A013", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Kerala Coconut Groves",       "lat": 9.85,  "lng": 76.82, "date": "2023-11-10", "event_type": "none",   "category": "agriculture", "resolution_m": 24},
    {"id": "A014", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Odisha Maize Fields",         "lat": 20.82, "lng": 85.08, "date": "2024-01-15", "event_type": "none",   "category": "agriculture", "resolution_m": 10},
    {"id": "A015", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Bihar Lentil Fields",         "lat": 25.68, "lng": 86.28, "date": "2023-12-05", "event_type": "none",   "category": "agriculture", "resolution_m": 30},
    {"id": "A016", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Himachal Apple Orchards",     "lat": 31.52, "lng": 77.18, "date": "2024-05-08", "event_type": "none",   "category": "agriculture", "resolution_m": 10},
    {"id": "A017", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Uttarakhand Terraced Fields", "lat": 30.22, "lng": 78.88, "date": "2023-09-08", "event_type": "none",   "category": "agriculture", "resolution_m": 24},
    {"id": "A018", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Punjab Mustard Fields",       "lat": 30.62, "lng": 74.68, "date": "2024-02-15", "event_type": "none",   "category": "agriculture", "resolution_m": 10},
    {"id": "A019", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Ganga-Yamuna Doab Crops",     "lat": 28.22, "lng": 78.38, "date": "2023-11-22", "event_type": "none",   "category": "agriculture", "resolution_m": 30},
    {"id": "A020", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Telangana Dryland Farming",   "lat": 18.28, "lng": 79.08, "date": "2024-03-28", "event_type": "none",   "category": "agriculture", "resolution_m": 10},

    # ── COASTAL / WATER BODY scenes ────────────────────────────────────────
    {"id": "C001", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Kerala Backwaters",           "lat": 9.28,  "lng": 76.52, "date": "2024-01-18", "event_type": "none",   "category": "coastal",     "resolution_m": 10},
    {"id": "C002", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Sundarbans Delta, Bengal",    "lat": 21.72, "lng": 88.98, "date": "2024-02-05", "event_type": "none",   "category": "coastal",     "resolution_m": 24},
    {"id": "C003", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Chilika Lake, Odisha",        "lat": 19.72, "lng": 85.32, "date": "2023-11-28", "event_type": "none",   "category": "coastal",     "resolution_m": 30},
    {"id": "C004", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Gulf of Kutch, Gujarat",      "lat": 22.88, "lng": 69.72, "date": "2024-03-08", "event_type": "none",   "category": "coastal",     "resolution_m": 10},
    {"id": "C005", "satellite": "Sentinel-1A",  "sensor_type": "SAR",          "location": "Tamil Nadu Coast",            "lat": 11.22, "lng": 79.82, "date": "2023-12-20", "event_type": "none",   "category": "coastal",     "resolution_m": 5},
    {"id": "C006", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Goa Beach Coast",             "lat": 15.38, "lng": 73.82, "date": "2024-04-28", "event_type": "none",   "category": "coastal",     "resolution_m": 10},
    {"id": "C007", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Lakshadweep Atoll",           "lat": 10.58, "lng": 72.68, "date": "2024-02-18", "event_type": "none",   "category": "coastal",     "resolution_m": 24},
    {"id": "C008", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Andaman Sea Coast",           "lat": 11.72, "lng": 92.72, "date": "2023-10-22", "event_type": "none",   "category": "coastal",     "resolution_m": 10},
    {"id": "C009", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Mumbai Harbour Bay",          "lat": 18.92, "lng": 72.85, "date": "2024-05-15", "event_type": "none",   "category": "coastal",     "resolution_m": 30},
    {"id": "C010", "satellite": "Sentinel-1B",  "sensor_type": "SAR",          "location": "Odisha Coast Cyclone Zone",   "lat": 20.42, "lng": 86.88, "date": "2023-10-08", "event_type": "none",   "category": "coastal",     "resolution_m": 5},
    {"id": "C011", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Andhra Pradesh Coast",        "lat": 15.92, "lng": 80.48, "date": "2024-01-28", "event_type": "none",   "category": "coastal",     "resolution_m": 10},
    {"id": "C012", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Mahanadi Delta Coast",        "lat": 20.22, "lng": 86.62, "date": "2023-12-15", "event_type": "none",   "category": "coastal",     "resolution_m": 24},
    {"id": "C013", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Kaveri Delta, Tamil Nadu",    "lat": 10.88, "lng": 79.88, "date": "2024-03-18", "event_type": "none",   "category": "coastal",     "resolution_m": 30},
    {"id": "C014", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Vembanad Lake, Kerala",       "lat": 9.62,  "lng": 76.38, "date": "2023-11-08", "event_type": "none",   "category": "coastal",     "resolution_m": 10},
    {"id": "C015", "satellite": "Sentinel-1A",  "sensor_type": "SAR",          "location": "Bengal Bay Estuary",          "lat": 22.12, "lng": 88.52, "date": "2024-04-08", "event_type": "none",   "category": "coastal",     "resolution_m": 5},
    {"id": "C016", "satellite": "Sentinel-2A",  "sensor_type": "Optical",      "location": "Rann of Kutch Salt Flats",    "lat": 23.72, "lng": 70.22, "date": "2024-02-28", "event_type": "none",   "category": "coastal",     "resolution_m": 10},
    {"id": "C017", "satellite": "ResourceSat-2A","sensor_type":"Multispectral", "location": "Godavari Delta Coast",        "lat": 16.78, "lng": 81.82, "date": "2023-12-28", "event_type": "none",   "category": "coastal",     "resolution_m": 24},
    {"id": "C018", "satellite": "Landsat-9",    "sensor_type": "Optical",      "location": "Pulicat Lake, Andhra",        "lat": 13.68, "lng": 80.28, "date": "2024-01-08", "event_type": "none",   "category": "coastal",     "resolution_m": 30},
    {"id": "C019", "satellite": "Sentinel-2B",  "sensor_type": "Optical",      "location": "Porbandar Coast, Gujarat",    "lat": 21.64, "lng": 69.61, "date": "2023-11-18", "event_type": "none",   "category": "coastal",     "resolution_m": 10},
    {"id": "C020", "satellite": "Sentinel-1B",  "sensor_type": "SAR",          "location": "Cauvery Delta Coast",         "lat": 10.92, "lng": 79.72, "date": "2024-03-25", "event_type": "none",   "category": "coastal",     "resolution_m": 5},
]


class ArchiveStore:
    """
    In-memory archive of satellite scene reference embeddings.

    On first access, builds 100 scene embeddings from domain-knowledge feature profiles.
    Each scene gets a deterministic embedding based on its category + small variation.

    WHY DETERMINISTIC VARIATION:
      Two flood scenes shouldn't have IDENTICAL embeddings — they're different floods.
      We add tiny deterministic noise based on the scene ID hash:
        rng = numpy.random.default_rng(seed=hash(scene_id) % 2^32)
        noise = rng.normal(0, 0.025, 32)
      This ensures:
        1. Same scene_id → same embedding (deterministic)
        2. Different flood scenes → slightly different embeddings (distinct)
        3. All flood scenes cluster together (noise < signal for discriminative dims)
    """

    def __init__(self) -> None:
        self._initialized = False
        self._entries: list[dict[str, Any]] = []
        self._embeddings: np.ndarray = np.zeros((0, 32))
        self._generator = EmbeddingGenerator()

    def initialize(self) -> None:
        """Build archive embeddings from feature profiles. Called once at startup."""
        if self._initialized:
            return

        entries = []
        embeddings = []

        for scene in _SCENE_CATALOG:
            scene_id  = scene["id"]
            category  = scene["category"]
            profile   = SCENE_PROFILES[category].copy()

            # Add tiny deterministic per-scene variation
            # seed = Python hash of scene_id, clamped to valid numpy seed range
            seed = abs(hash(scene_id)) % (2**31)
            rng = np.random.default_rng(seed=seed)
            noise = rng.normal(0, 0.025, 32).astype(np.float32)
            fvec = np.clip(profile + noise, 0.0, 1.0)

            # Compute embedding using the same generator as the pipeline
            embedding, _ = self._generator.generate(fvec.tolist())
            emb_arr = np.array(embedding, dtype=np.float32)

            # Build the archive entry
            thumb_list = _THUMBS.get(category, [""])
            thumb_idx  = abs(hash(scene_id)) % len(thumb_list)

            entry = {
                "id":           scene_id,
                "satellite":    scene["satellite"],
                "sensor_type":  scene["sensor_type"],
                "location":     scene["location"],
                "lat":          scene["lat"],
                "lng":          scene["lng"],
                "date":         scene["date"],
                "event_type":   scene["event_type"],
                "category":     category,
                "resolution_m": scene["resolution_m"],
                "thumbnail":    thumb_list[thumb_idx],
                "cloud_cover":  float(rng.integers(0, 15)),
                "feature_vector": fvec.tolist(),
                "embedding":    embedding,
            }
            entries.append(entry)
            embeddings.append(emb_arr)

        self._entries    = entries
        self._embeddings = np.array(embeddings, dtype=np.float32)
        self._initialized = True

    @property
    def entries(self) -> list[dict[str, Any]]:
        if not self._initialized:
            self.initialize()
        return self._entries

    @property
    def embeddings(self) -> np.ndarray:
        """Returns (100, 32) matrix of archive unit embeddings."""
        if not self._initialized:
            self.initialize()
        return self._embeddings

    @property
    def size(self) -> int:
        return len(self._entries)


# Module-level singleton — initialized once at server startup
archive_store = ArchiveStore()
